### ISSUE TITLE
AIX Compilation

### ISSUE THREAD

**Issue by draakuns** [res0nat0r/tsunami-udp#1]
Hi, 

I've tried to compile tsunami-udp on AIX with GCC (4.2.3, 4.8.2 and 4.8.3) and xlC 12 with no success. When I run sh recompile.sh, it fails with: 

```
Making all in include
make: Nothing to be done for 'all'.
Making all in common
gcc -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -I. -I../include   -DARCH_IS_BIG_ENDIAN  -g -Wall -O3 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -MT md5.o -MD -MP -MF .deps/md5.Tpo -c -o md5.o md5.c
mv -f .deps/md5.Tpo .deps/md5.Po
gcc -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -I. -I../include   -DARCH_IS_BIG_ENDIAN  -g -Wall -O3 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -MT common.o -MD -MP -MF .deps/common.Tpo -c -o common.o common.c
In file included from common.c:65:0:
../include/tsunami.h:141:47: error: expected ')' before 'value'
 u_int64_t  htonll                  (u_int64_t value);
                                               ^
../include/tsunami.h:143:47: error: expected ')' before 'value'
 u_int64_t  ntohll                  (u_int64_t value);
                                               ^
common.c:149:28: error: expected ')' before 'value'
 u_int64_t htonll(u_int64_t value)
                            ^
common.c:194:28: error: expected ')' before 'value'
 u_int64_t ntohll(u_int64_t value)
                            ^
Makefile:381: recipe for target 'common.o' failed
make: *** [common.o] Error 1
make: 1254-004 The error code from the last command is 1.
```

The current (compilation related) package list:
make_64-4.0-1
gcc-gfortran-4.8.3-1
gcc-4.8.3-1
libgcc-4.8.3-1
libgomp-4.8.3-1
libstdc++-4.8.3-1
libstdc++-devel-4.8.3-1
gcc-cpp-4.8.3-1
libmpc-1.0.2-1
mpfr-3.1.2-1
autoconf-2.69-1
automake-1.14-1
m4-1.4.17-1
gmp-5.1.3-1

I can try everything you need in order to fix this issue, if needed.

Thanks in advance.

**Comment by rodrigo4oki** [comment]
Hello,

Did you resolved the compilation issue? I´m trying to compile tsunami UDP on AIX 7.1 and I´m stucked at the same point that you mentioned.

Regards,

**Comment by rodrigo4oki** [comment]
Here is the error running make command:

 make
Making all in include
        cd ../ && make  am--refresh
        cd ../ && make  am--refresh
Target "all" is up to date.
Making all in common
        cd ../ && make  am--refresh
        cd ../ && make  am--refresh
        gcc -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\"  -I.@am__isrc@ -I../include     -g -Wall -O3 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -MT md5.o -MD -MP -MF .deps/md5.Tpo -c -o md5.o md5.c
        mv -f .deps/md5.Tpo .deps/md5.Po
        gcc -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\"  -I.@am__isrc@ -I../include     -g -Wall -O3 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -MT common.o -MD -MP -MF .deps/common.Tpo -c -o common.o common.c
In file included from common.c:65:0:
../include/tsunami.h:141:47: error: expected ')' before 'value'
 u_int64_t  htonll                  (u_int64_t value);
                                               ^
../include/tsunami.h:143:47: error: expected ')' before 'value'
 u_int64_t  ntohll                  (u_int64_t value);
                                               ^
common.c:149:28: error: expected ')' before 'value'
 u_int64_t htonll(u_int64_t value)
                            ^
common.c:194:28: error: expected ')' before 'value'
 u_int64_t ntohll(u_int64_t value)
                            ^
make: The error code from the last command is 1.

Stop.
make: The error code from the last command is 1.

Stop.

**Comment by draakuns** [comment]
Sorry, It was not really needed on my project, so was a try that took too much time... So I quit trying.

If you make any progress, please drop a line over here to try on my machines ;)

Regards

**Comment by Rnldm** [comment]
Hi, I've the same problem has someone a solution for this? I'm using AIX 7.1

**Comment by draakuns** [comment]
No feedback from dev at all, so closing to clean my issues list. Good luck.
